### ISSUE TITLE
Implement missing RMW functions

### ISSUE THREAD

**Issue by jacquelinekay** [eProsima/ROS-RMW-Fast-RTPS-cpp#14]
The following functions in src/functions.cpp are not implemented yet:

https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/blob/master/rmw_fastrtps_cpp/src/functions.cpp#L1770-L1806

We haven't exercised these functions outside of the ros1bridge yet, but this limitation came up recently in ros2/system_tests#103.

**Comment by JaimeMartin** [comment]
Hi Jackie,

We are working on this. We will keep you posted.

**Comment by jacquelinekay** [comment]
Thanks!

Pinging @wjwwood too since I believe he needs this for his work on the Graph API.

**Comment by richiprosima** [comment]
service_is_available functionality for Fast-RTPS in #56.
@wjwwood I noticed that function wait_for_service calls only one time to rmw_service_is_available function. It should test more times, shouldn't it?

**Comment by richiprosima** [comment]
#56

**Comment by wjwwood** [comment]
@richiprosima `rmw_service_is_available` is a non-blocking call, so no it only checks once. The idea is that you're waiting for changes to the graph and only call this function once at the beginning and once each time the graph changes, until it either returns true or you've waited as long as you're willing to wait. See the implementation for `wait_for_service` in rclcpp:

https://github.com/ros2/rclcpp/blob/master/rclcpp/src/rclcpp/client.cpp#L65-L107
