### ISSUE TITLE
Reset fixed guard conditions

### ISSUE THREAD

**Issue by gerkey** [eProsima/ROS-RMW-Fast-RTPS-cpp#16]
In ros2/rmw_connext#125, we found that the fixed guard conditions were never being reset to false, leading to `rmw_wait()` in many situations waking up immediately, every call. We fixed it in [rmw_connext](https://github.com/ros2/rmw_connext/pull/129) and [rmw_opensplice](https://github.com/ros2/rmw_opensplice/pull/111) by resetting the fixed guard conditions to false before existing `rmw_wait()`.

For FastRTPS, it looks like you'll want to repeat [this block](https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/blob/master/rmw_fastrtps_cpp/src/functions.cpp#L1751-L1765) for the `fixed_guard_conditions`. I would submit a PR with that fix, but I'm not familiar enough with the code to know that that's the right answer.

**Comment by dirk-thomas** [comment]
Fixed guard conditions have been removed some time ago (e.g. ros2/rmw_connext#147). Closing...
