### ISSUE TITLE
Services not implemented in FastRTPS yet?

### ISSUE THREAD

**Issue by firesurfer** [eProsima/ROS-RMW-Fast-RTPS-cpp#55]
Am I right in the assumption that services aren't fully implemented yet in the FastRTPS middleware?

The add_two_ints_client example throws this exception at the moment:

```
add_two_ints_client
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  rcl_service_server_is_available failed: not implemented, at /home/firesurfer/workspace/ros2_ws/src/eProsima/ROS-RMW-Fast-RTPS-cpp/rmw_fastrtps_cpp/src/functions.cpp:2481
Abgebrochen
```

After reading #48 I would expect that services are at least somehow implemented?

In case this isn't just a bug, what is currently missing in order to use services with fastRTPS?

**Comment by dirk-thomas** [comment]
Services themselves are implemented in FastRTPS. But some additional introspection method are not yet available. E.g. `rmw_service_server_is_available` which is being used to avoid race conditions (ensure that the server is up and running before the client sends requests): https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/blob/e336a8b0f93c8179cc2b4a62d02272403ed356bb/rmw_fastrtps_cpp/src/functions.cpp#L2472-L2483

This issue should already be covered by #14 so I will close this one.
