### ISSUE TITLE
Why limited the maximum size of a STRING

### ISSUE THREAD

**Issue by Theosakamg** [eProsima/ROS-RMW-Fast-RTPS-cpp#60]
I not find any reference in ROS2 & IDL documentation.
But actualy the code is limited to 255.

in https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/blob/master/rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.h
```
case ::rosidl_typesupport_introspection_cpp::ROS_TYPE_STRING:
{
    auto && str = StringHelper<MembersType>::convert_to_std_string(field);

    // Control maximum length.
    if((member->string_upper_bound_ && str.length() > member->string_upper_bound_ + 1) || str.length() > 256)
     {
        throw std::runtime_error("string overcomes the maximum length");
     }
     ser << str;
}
break;
```

I remove the limitation and I send a String of 1024 without any problem.

**Comment by dirk-thomas** [comment]
Thanks for reporting this. We explicitly test for support of strings > 255 characters (by sending a string with 256: https://github.com/ros2/system_tests/blob/155879c626d991c74f5a4a08e6d5a8f4ac663382/test_communication/test/message_fixtures.hpp#L117-L121). But this rmw impl. allows 256 but not 257 :confused:

I have no idea why preventing > 256 would make any sense and created #61 to remove the arbitrary upper size limit. Maybe @richiprosima can comment on why he added this (https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/commit/50a7ff3ac65aa84095bc74e21b35ad498aa4597e#diff-e662f7cc6ba490df2f1b9aff2eafd2a3R247).
